<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Station;

class StationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $stations = [
        [
                        'station_id' => 'IALBATER2',
                        'name' => 'Albatera – Centro',
                        'country' => 'ES',
                        'lat' => 38.179,
                        'lon' => -0.868,
                        'elevation' => 21,
                        'api_key' => '106e5d8a46c24475ae5d8a46c2d47525',
                    ],
        [
                        'station_id' => 'IALBAT7',
                        'name' => 'Albatera – IES Antonio Serna',
                        'country' => 'ES',
                        'lat' => 38.185382,
                        'lon' => -0.870093,
                        'elevation' => 26,
                        'api_key' => '405a76f182374ba79a76f182378ba750',
                    ],
        [
                        'station_id' => 'IALBAT8',
                        'name' => 'Albatera – Finca El Prao',
                        'country' => 'ES',
                        'lat' => 38.214561,
                        'lon' => -0.852131,
                        'elevation' => 72,
                        'api_key' => 'fbfaa3341dd24944baa3341dd2094491',
                    ],
        [
                        'station_id' => 'IALBAT9',
                        'name' => 'Eléctrica Albaterense',
                        'country' => 'ES',
                        'lat' => 38.208078,
                        'lon' => -0.865172,
                        'elevation' => 61,
                        'api_key' => 'e302b92bba674a3782b92bba67ca37ad',
                    ],
        [
                        'station_id' => 'IALBAT10',
                        'name' => 'Albatera – La Molineta',
                        'country' => 'ES',
                        'lat' => 38.194772,
                        'lon' => -0.850976,
                        'elevation' => 21,
                        'api_key' => '1fdc046964c047839c046964c047833d',
                    ],
        [
                        'station_id' => 'IALGOR2',
                        'name' => 'Algorfa - Centro',
                        'country' => 'ES',
                        'lat' => 38.087312,
                        'lon' => -0.795652,
                        'elevation' => 26,
                        'api_key' => '1ee326c7f81e42c7a326c7f81e42c715',
                    ],
        [
                        'station_id' => null,
                        'name' => 'Algorfa – Lomas de la Juliana',
                        'country' => 'ES',
                        'lat' => 38.070806,
                        'lon' => -0.784972,
                        'elevation' => 80,
                        'api_key' => 'Ecowitt',
                    ],
        [
                        'station_id' => 'IALMORAD2',
                        'name' => 'Almoradí – Centro',
                        'country' => 'ES',
                        'lat' => 38.11,
                        'lon' => -0.791,
                        'elevation' => 12,
                        'api_key' => 'daaf298bc00b4ccdaf298bc00b2ccdae',
                    ],
        [
                        'station_id' => 'IALMOR1',
                        'name' => 'Almoradí – Los Gomares',
                        'country' => 'ES',
                        'lat' => 38.114,
                        'lon' => -0.798,
                        'elevation' => 7,
                        'api_key' => 'ea0823d7a86848b08823d7a868e8b06d',
                    ],
        [
                        'station_id' => 'IALMOR10',
                        'name' => 'Almoradí – San Francisco',
                        'country' => 'ES',
                        'lat' => 38.107302,
                        'lon' => -0.793532,
                        'elevation' => 10,
                        'api_key' => '4ca7b501600e49daa7b501600e99da2a',
                    ],
        [
                        'station_id' => null,
                        'name' => 'Almoradí – La Venta',
                        'country' => 'ES',
                        'lat' => 38.107745,
                        'lon' => -0.81342,
                        'elevation' => 8,
                        'api_key' => 'Ecowitt',
                    ],
        [
                        'station_id' => 'IALMOR12',
                        'name' => 'Maromas - Fitoser Agro S.L.',
                        'country' => 'ES',
                        'lat' => 38.096129,
                        'lon' => -0.797502,
                        'elevation' => 11,
                        'api_key' => '356cafe7b1794ce7acafe7b179cce7eb',
                    ],
        [
                        'station_id' => 'IBENEJ2',
                        'name' => 'Benejúzar – Centro',
                        'country' => 'ES',
                        'lat' => 38.077758,
                        'lon' => 38.077758,
                        'elevation' => 25,
                        'api_key' => '96cedef1fb4246178edef1fb428617a3',
                    ],
        [
                        'station_id' => 'IBENEJ1',
                        'name' => 'Benejúzar – Las Monjas',
                        'country' => 'ES',
                        'lat' => 38.073,
                        'lon' => -0.841,
                        'elevation' => 30,
                        'api_key' => 'cb67ebfdb47641fda7ebfdb476e1fd38',
                    ],
        [
                        'station_id' => 'IBENFE6',
                        'name' => 'Benferri – CEIP Argentina',
                        'country' => 'ES',
                        'lat' => 38.144913,
                        'lon' => -0.961842,
                        'elevation' => 52,
                        'api_key' => 'b0298aab08b14cfba98aab08b15cfb76',
                    ],
        [
                        'station_id' => 'IBENFE5',
                        'name' => 'Benferri – Centro',
                        'country' => 'ES',
                        'lat' => 38.142035,
                        'lon' => -0.961573,
                        'elevation' => 53,
                        'api_key' => 'e0195322deaa406f995322deaa806f17',
                    ],
        [
                        'station_id' => 'IBENFE7',
                        'name' => 'Benferri – Urb. Benfisol',
                        'country' => 'ES',
                        'lat' => 38.147206,
                        'lon' => -0.960363,
                        'elevation' => 51,
                        'api_key' => 'ecadba451d694128adba451d69d1282c',
                    ],
        [
                        'station_id' => 'IBENIJ2',
                        'name' => 'Benijófar - Centro',
                        'country' => 'ES',
                        'lat' => 38.077846,
                        'lon' => -0.736786,
                        'elevation' => 37,
                        'api_key' => '4a5c59ad398a4dbc9c59ad398a1dbc86',
                    ],
        [
                        'station_id' => 'IBENIJ3',
                        'name' => 'Benijófar – Urb. Monteazul',
                        'country' => 'ES',
                        'lat' => 38.066201,
                        'lon' => -0.740188,
                        'elevation' => 32,
                        'api_key' => '4a5c59ad398a4dbc9c59ad398a1dbc86',
                    ],
        [
                        'station_id' => 'IBIGAS10',
                        'name' => 'Bigastro – Calle Sol',
                        'country' => 'ES',
                        'lat' => 38.061563,
                        'lon' => -0.901398,
                        'elevation' => 40,
                        'api_key' => 'b2776a2c49dd4180b76a2c49dd7180db',
                    ],
        [
                        'station_id' => 'IBIGAS5',
                        'name' => 'Bigastro – IES Paco Ruiz',
                        'country' => 'ES',
                        'lat' => 38.063682,
                        'lon' => -0.9059,
                        'elevation' => 26,
                        'api_key' => '2f86cd5ce31e42cf86cd5ce31ee2cf95',
                    ],
        [
                        'station_id' => 'IBIGAS2',
                        'name' => 'Bigastro – Lo Chusco',
                        'country' => 'ES',
                        'lat' => 38.059,
                        'lon' => -0.901,
                        'elevation' => 51,
                        'api_key' => '02350a61acc641bcb50a61acc621bc0d',
                    ],
        [
                        'station_id' => 'IBIGAS9',
                        'name' => 'Bigastro – Parque Huerto del Cura',
                        'country' => 'ES',
                        'lat' => 38.064039,
                        'lon' => -0.896092,
                        'elevation' => 22,
                        'api_key' => '09078909c5a342a0878909c5a382a0e7',
                    ],
        [
                        'station_id' => 'IBIGAS13',
                        'name' => 'Bigastro – Parque Río Segura',
                        'country' => 'ES',
                        'lat' => 38.064077,
                        'lon' => -0.892069,
                        'elevation' => 22,
                        'api_key' => '5ed84d824b6a4b8f984d824b6acb8fd0',
                    ],
        [
                        'station_id' => 'IBIGAS4',
                        'name' => 'Bigastro – La Pedrera',
                        'country' => 'ES',
                        'lat' => 38.05,
                        'lon' => -0.895,
                        'elevation' => 103,
                        'api_key' => '30213a481ec44b02a13a481ec4eb0297',
                    ],
        [
                        'station_id' => 'IBIGAS8',
                        'name' => 'Bigastro – Polígono Industrial El Apatel',
                        'country' => 'ES',
                        'lat' => 38.057005,
                        'lon' => -0.883503,
                        'elevation' => 32,
                        'api_key' => 'b2776a2c49dd4180b76a2c49dd7180db',
                    ],
        [
                        'station_id' => 'IBIGAS7',
                        'name' => 'Bigastro – Polideportivo El Molino',
                        'country' => 'ES',
                        'lat' => 38.07099,
                        'lon' => -0.897879,
                        'elevation' => 19,
                        'api_key' => 'b2776a2c49dd4180b76a2c49dd7180db',
                    ],
        [
                        'station_id' => null,
                        'name' => 'Callosa de Segura – Calle Rambla Baja',
                        'country' => 'ES',
                        'lat' => 38.125121,
                        'lon' => -0.878692,
                        'elevation' => 17,
                        'api_key' => 'Ecowitt',
                    ],
        [
                        'station_id' => 'ICALLOSA5',
                        'name' => 'Callosa de Segura – Casa de Cultura',
                        'country' => 'ES',
                        'lat' => 38.123265,
                        'lon' => -0.879141,
                        'elevation' => 18,
                        'api_key' => '643d69c4bfc647d6bd69c4bfc607d6d0',
                    ],
        [
                        'station_id' => 'ICALLO17',
                        'name' => 'Callosa de Segura – Ferrocarril',
                        'country' => 'ES',
                        'lat' => 38.125027,
                        'lon' => -0.872964,
                        'elevation' => 14,
                        'api_key' => '67abe5a4694a4692abe5a4694ac69277',
                    ],
        [
                        'station_id' => 'ICALLO5',
                        'name' => 'Callosa de Segura – Jardín Glorieta',
                        'country' => 'ES',
                        'lat' => 38.127809,
                        'lon' => -0.87844,
                        'elevation' => 17,
                        'api_key' => '305770ef442e47739770ef442ee7733c',
                    ],
        [
                        'station_id' => 'ICALLO18',
                        'name' => 'Callosa de Segura – Restaurante Frasquitín',
                        'country' => 'ES',
                        'lat' => 38.1324,
                        'lon' => -0.850214,
                        'elevation' => 10,
                        'api_key' => '47df08f9dabd48c39f08f9dabd28c314',
                    ],
        [
                        'station_id' => null,
                        'name' => 'Catral – Barrio Puente del Rollo',
                        'country' => 'ES',
                        'lat' => 38.162479,
                        'lon' => -0.802815,
                        'elevation' => 6,
                        'api_key' => 'Ecowitt',
                    ],
        [
                        'station_id' => 'ICATRA1',
                        'name' => 'Catral – Centro',
                        'country' => 'ES',
                        'lat' => 38.161,
                        'lon' => -0.802,
                        'elevation' => 12,
                        'api_key' => 'ec7d858cd5b24422bd858cd5b2942266',
                    ],
        [
                        'station_id' => 'ICATRA6',
                        'name' => 'Catral – Los Tonecas',
                        'country' => 'ES',
                        'lat' => 38.162549,
                        'lon' => -0.769137,
                        'elevation' => 3,
                        'api_key' => 'fe9ba2c5c4f8493b9ba2c5c4f8993bc0',
                    ],
        [
                        'station_id' => 'ICOX3',
                        'name' => 'Cox – Casa de Cultura',
                        'country' => 'ES',
                        'lat' => 38.141,
                        'lon' => -0.887,
                        'elevation' => 21,
                        'api_key' => 'cf26980d85b4444ba6980d85b4544b6c',
                    ],
        [
                        'station_id' => 'ICOX4',
                        'name' => 'Cox – El Jasminao',
                        'country' => 'ES',
                        'lat' => 38.146,
                        'lon' => -0.888,
                        'elevation' => 17,
                        'api_key' => 'cf26980d85b4444ba6980d85b4544b6c',
                    ],
        [
                        'station_id' => 'ICOX19',
                        'name' => 'Cox – Piscina de Pepín',
                        'country' => 'ES',
                        'lat' => 38.133887,
                        'lon' => -0.893762,
                        'elevation' => 85,
                        'api_key' => 'f383571e6a4544ac83571e6a4584ac0d',
                    ],
        [
                        'station_id' => null,
                        'name' => 'Cox – Telecolor VegaFibra',
                        'country' => 'ES',
                        'lat' => 38.143166,
                        'lon' => -0.888423,
                        'elevation' => 17,
                        'api_key' => 'Ecowitt',
                    ],
        [
                        'station_id' => null,
                        'name' => 'Cox – El Salar',
                        'country' => 'ES',
                        'lat' => 38.15223,
                        'lon' => -0.86377,
                        'elevation' => 10,
                        'api_key' => 'Ecowitt',
                    ],
        [
                        'station_id' => 'ICREVI6',
                        'name' => 'Crevillente – Cañada de Joana',
                        'country' => 'ES',
                        'lat' => 38.220165,
                        'lon' => -0.797543,
                        'elevation' => 36,
                        'api_key' => '731dddf9942d4f3d9dddf9942ddf3d27',
                    ],
        [
                        'station_id' => 'ICREVI11',
                        'name' => 'Crevillente – Paseo Fontenay',
                        'country' => 'ES',
                        'lat' => 38.246034,
                        'lon' => -0.809058,
                        'elevation' => 118,
                        'api_key' => '0ab66d20e4c74536b66d20e4c72536cd',
                    ],
        [
                        'station_id' => null,
                        'name' => 'Crevillente – El Realengo',
                        'country' => 'ES',
                        'lat' => 38.200429,
                        'lon' => -0.797696,
                        'elevation' => 6,
                        'api_key' => null,
                    ],
        [
                        'station_id' => 'ICREVI10',
                        'name' => 'Crevillente – La Deula',
                        'country' => 'ES',
                        'lat' => 38.229046,
                        'lon' => -0.812472,
                        'elevation' => 64,
                        'api_key' => 'e0195322deaa406f995322deaa806f17',
                    ],
        [
                        'station_id' => 'ICREVI9',
                        'name' => 'Crevillente – La Llobera',
                        'country' => 'ES',
                        'lat' => 38.249041,
                        'lon' => -0.821925,
                        'elevation' => 149,
                        'api_key' => '570a73602e16482e8a73602e16082ea2',
                    ],
        [
                        'station_id' => 'ICREVI3',
                        'name' => 'Crevillente – Pico La Vella',
                        'country' => 'ES',
                        'lat' => 38.277946,
                        'lon' => -0.858593,
                        'elevation' => 838,
                        'api_key' => 'cab94b7abcb14f1cb94b7abcb16f1c2f',
                    ],
        [
                        'station_id' => 'ICREVI4',
                        'name' => 'Crevillente – San Felipe Neri',
                        'country' => 'ES',
                        'lat' => 38.177776,
                        'lon' => -0.797696,
                        'elevation' => 4,
                        'api_key' => 'cab94b7abcb14f1cb94b7abcb16f1c2f',
                    ],
        [
                        'station_id' => 'IDAYAN2',
                        'name' => 'Daya Nueva – Centro',
                        'country' => 'ES',
                        'lat' => 38.114546,
                        'lon' => -0.762867,
                        'elevation' => 7,
                        'api_key' => '45e51bc97dc143baa51bc97dc1c3ba92',
                    ],
        [
                        'station_id' => 'IDAYAV2',
                        'name' => 'Daya Vieja – Centro',
                        'country' => 'ES',
                        'lat' => 38.105085,
                        'lon' => -0.738039,
                        'elevation' => 5,
                        'api_key' => 'a36b793720ef4f99ab793720ef2f99b1',
                    ],
        [
                        'station_id' => null,
                        'name' => 'Daya Vieja – Finca Villa Vera',
                        'country' => 'ES',
                        'lat' => 38.10018,
                        'lon' => -0.745439,
                        'elevation' => 6,
                        'api_key' => 'Ecowitt',
                    ],
        [
                        'station_id' => 'IDOLOR4',
                        'name' => 'Dolores – Cuatro Caminos',
                        'country' => 'ES',
                        'lat' => 38.123763,
                        'lon' => -0.749157,
                        'elevation' => 3,
                        'api_key' => 'e352ebcb1d5247dc92ebcb1d52e7dc7b',
                    ],
        [
                        'station_id' => 'IDOLOR26',
                        'name' => 'Dolores – IES San Pascual',
                        'country' => 'ES',
                        'lat' => 38.135147,
                        'lon' => -0.767386,
                        'elevation' => 5,
                        'api_key' => '370405b1f55a40488405b1f55a004894',
                    ],
        [
                        'station_id' => 'IDOLOR18',
                        'name' => 'Dolores – Vereda La Alberca',
                        'country' => 'ES',
                        'lat' => 38.133582,
                        'lon' => -0.753641,
                        'elevation' => 3,
                        'api_key' => 'aab20650189349bcb206501893b9bc95',
                    ],
        [
                        'station_id' => 'IDOLOR17',
                        'name' => 'Dolores – Vereda Rondaina',
                        'country' => 'ES',
                        'lat' => 38.153386,
                        'lon' => -0.756633,
                        'elevation' => 2,
                        'api_key' => '175261dfe84042bd9261dfe840d2bd65',
                    ],
        [
                        'station_id' => null,
                        'name' => 'Palacios',
                        'country' => 'ES',
                        'lat' => 38.092294,
                        'lon' => -0.728611,
                        'elevation' => 7,
                        'api_key' => 'Ecowitt',
                    ],
        [
                        'station_id' => 'IFORME47',
                        'name' => 'Formentera del Segura – Calvario Viejo',
                        'country' => 'ES',
                        'lat' => 38.092059,
                        'lon' => -0.722721,
                        'elevation' => 6,
                        'api_key' => 'cd3a830dc71c4491ba830dc71cb491e3',
                    ],
        [
                        'station_id' => 'IFORME54',
                        'name' => 'Formentera del Segura – Centro',
                        'country' => 'ES',
                        'lat' => 38.083833,
                        'lon' => -0.746666,
                        'elevation' => 9,
                        'api_key' => 'b8bc43422a454cfabc43422a459cfad4',
                    ],
        [
                        'station_id' => 'IFORME42',
                        'name' => 'Formentera del Segura – Los Palacios',
                        'country' => 'ES',
                        'lat' => 38.089157,
                        'lon' => -0.725487,
                        'elevation' => 7,
                        'api_key' => 'bbf3299520324b9eb329952032eb9ea7',
                    ],
        [
                        'station_id' => 'IGRANJ4',
                        'name' => 'Granja de Rocamora – Centro',
                        'country' => 'ES',
                        'lat' => 38.152949,
                        'lon' => -0.889043,
                        'elevation' => 16,
                        'api_key' => 'dde7b1782322423ea7b1782322423e17',
                    ],
        [
                        'station_id' => 'IGUARD3',
                        'name' => 'Guardamar del Segura – Centro',
                        'country' => 'ES',
                        'lat' => 38.085414,
                        'lon' => -0.654437,
                        'elevation' => 26,
                        'api_key' => '3d3d67551c6a4604bd67551c6a7604b2',
                    ],
        [
                        'station_id' => 'IGUARD40',
                        'name' => 'Guardamar del Segura – AgroPaco',
                        'country' => 'ES',
                        'lat' => 38.102,
                        'lon' => -0.687,
                        'elevation' => 4,
                        'api_key' => '622755936aaa44d0a755936aaa24d0eb',
                    ],
        [
                        'station_id' => 'IJACAR4',
                        'name' => 'Jacarilla – El Copo',
                        'country' => 'ES',
                        'lat' => 38.06,
                        'lon' => -0.876,
                        'elevation' => 25,
                        'api_key' => '2e3d4d4abfd64024bd4d4abfd630244d',
                    ],
        [
                        'station_id' => 'IJACAR3',
                        'name' => 'Jacarilla – Centro',
                        'country' => 'ES',
                        'lat' => 38.062,
                        'lon' => -0.868,
                        'elevation' => 32,
                        'api_key' => '2a5128ba8dcb4e749128ba8dcbce741e',
                    ],
        [
                        'station_id' => 'IJACAR17',
                        'name' => 'Jacarilla – Palacio Marqués de Fontalba',
                        'country' => 'ES',
                        'lat' => 38.062119,
                        'lon' => -0.865344,
                        'elevation' => 22,
                        'api_key' => '8bbe8b0a5a20444ebe8b0a5a20f44ea7',
                    ],
        [
                        'station_id' => null,
                        'name' => 'Jacarilla – Jacarilleta',
                        'country' => 'ES',
                        'lat' => 38.066678,
                        'lon' => -0.857713,
                        'elevation' => 18,
                        'api_key' => 'Ecowitt',
                    ],
        [
                        'station_id' => null,
                        'name' => 'Los Montesinos – IES Remedios Muñoz',
                        'country' => 'ES',
                        'lat' => 38.02619,
                        'lon' => -0.747514,
                        'elevation' => 16,
                        'api_key' => 'Ecowitt',
                    ],
        [
                        'station_id' => 'IORIHU71',
                        'name' => 'Orihuela  - Alto de las Majadas',
                        'country' => 'ES',
                        'lat' => 37.955267,
                        'lon' => -0.752079,
                        'elevation' => 64,
                        'api_key' => '2cf6135e55154229b6135e5515a229ae',
                    ],
        [
                        'station_id' => 'IORIHU42',
                        'name' => 'Orihuela – Arneva – Barranco',
                        'country' => 'ES',
                        'lat' => 38.054237,
                        'lon' => -0.941882,
                        'elevation' => 35,
                        'api_key' => 'd245c16ca14b4feb85c16ca14befebad',
                    ],
        [
                        'station_id' => 'IORIHU21',
                        'name' => 'Orihuela – Arneva – Centro',
                        'country' => 'ES',
                        'lat' => 38.054372,
                        'lon' => -0.940491,
                        'elevation' => 40,
                        'api_key' => '02350a61acc641bcb50a61acc621bc0d',
                    ],
        [
                        'station_id' => 'IORIHU141',
                        'name' => 'Orihuela – Cabo Roig',
                        'country' => 'ES',
                        'lat' => 37.911468,
                        'lon' => -0.724498,
                        'elevation' => 15,
                        'api_key' => '1702472f3517490c82472f3517f90c3e',
                    ],
        [
                        'station_id' => 'IORIHU67',
                        'name' => 'Orihuela – Camino Viejo de Callosa',
                        'country' => 'ES',
                        'lat' => 38.090982,
                        'lon' => -0.934091,
                        'elevation' => 21,
                        'api_key' => '67abe5a4694a4692abe5a4694ac69277',
                    ],
        [
                        'station_id' => null,
                        'name' => 'Orihuela – Casa Corro',
                        'country' => 'ES',
                        'lat' => 38.100435,
                        'lon' => -0.934193,
                        'elevation' => 23,
                        'api_key' => 'Ecowitt',
                    ],
        [
                        'station_id' => 'IORIHU101',
                        'name' => 'Orihuela – Club Náutico Campoamor',
                        'country' => 'ES',
                        'lat' => 37.899376,
                        'lon' => -0.749414,
                        'elevation' => 2,
                        'api_key' => '175261dfe84042bd9261dfe840d2bd65',
                    ],
        [
                        'station_id' => 'IORIHU66',
                        'name' => 'Orihuela – Correntías Altas',
                        'country' => 'ES',
                        'lat' => 38.070112,
                        'lon' => -0.860969,
                        'elevation' => 19,
                        'api_key' => '75ff78253404498fbf78253404398fcf',
                    ],
        [
                        'station_id' => 'IORIHU34',
                        'name' => 'Orihuela – Dehesa de Campoamor',
                        'country' => 'ES',
                        'lat' => 38.032,
                        'lon' => -0.944,
                        'elevation' => 28,
                        'api_key' => '6ea1a3b4577b4b32a1a3b4577bcb3253',
                    ],
        [
                        'station_id' => 'IORIHU41',
                        'name' => 'Orihuela – Desamparados – Carril Casiaro',
                        'country' => 'ES',
                        'lat' => 38.057,
                        'lon' => -0.979,
                        'elevation' => 24,
                        'api_key' => '0ca96f8bcdfc4587a96f8bcdfca58755',
                    ],
        [
                        'station_id' => 'IORIHU93',
                        'name' => 'Cementerio',
                        'country' => 'ES',
                        'lat' => 38.06363,
                        'lon' => -0.995945,
                        'elevation' => 29,
                        'api_key' => 'e320d77c60204c80a0d77c60203c809c',
                    ],
        [
                        'station_id' => null,
                        'name' => 'Orihuela – El Badén',
                        'country' => 'ES',
                        'lat' => 38.104227,
                        'lon' => -0.860075,
                        'elevation' => 12,
                        'api_key' => 'Ecowitt',
                    ],
        [
                        'station_id' => 'IORIHU140',
                        'name' => 'Orihuela – El Pocico',
                        'country' => 'ES',
                        'lat' => 38.057834,
                        'lon' => -0.890957,
                        'elevation' => 38,
                        'api_key' => '5ed84d824b6a4b8f984d824b6acb8fd0',
                    ],
        [
                        'station_id' => 'IORIHU110',
                        'name' => 'Orihuela – Finca Agrícola Los Pinos',
                        'country' => 'ES',
                        'lat' => 38.02942,
                        'lon' => -0.902295,
                        'elevation' => 122,
                        'api_key' => '2c58eb035bb5447998eb035bb5e4793a',
                    ],
        [
                        'station_id' => 'IORIHU97',
                        'name' => 'Orihuela – Finca Los Pinos',
                        'country' => 'ES',
                        'lat' => 38.126512,
                        'lon' => -0.995397,
                        'elevation' => 75,
                        'api_key' => 'bfba2262ca254b64ba2262ca255b64d0',
                    ],
        [
                        'station_id' => null,
                        'name' => 'Orihuela – Finca Pico del Águila',
                        'country' => 'ES',
                        'lat' => 38.081721,
                        'lon' => -1.011636,
                        'elevation' => 56,
                        'api_key' => 'Ecowitt',
                    ],
        [
                        'station_id' => 'IORIHU99',
                        'name' => 'Riquelme',
                        'country' => 'ES',
                        'lat' => 38.059,
                        'lon' => -0.92,
                        'elevation' => 25,
                        'api_key' => '4521a550a6ec4bf8a1a550a6ecebf8d7',
                    ],
        [
                        'station_id' => 'IORIHU95',
                        'name' => 'Orihuela – La Aparecida - Calle La Carretera',
                        'country' => 'ES',
                        'lat' => 38.081552,
                        'lon' => -1.003851,
                        'elevation' => 31,
                        'api_key' => '3ba44b2503114d4da44b250311dd4d74',
                    ],
        [
                        'station_id' => 'IORIHU121',
                        'name' => 'Señora de Belén',
                        'country' => 'ES',
                        'lat' => 38.077859,
                        'lon' => -1.007313,
                        'elevation' => 27,
                        'api_key' => 'e368e2bcd4d443efa8e2bcd4d4e3ef36',
                    ],
        [
                        'station_id' => 'IORIHU134',
                        'name' => 'Orihuela – La Baronesa – Weitec',
                        'country' => 'ES',
                        'lat' => 38.126947,
                        'lon' => -1.012089,
                        'elevation' => 89,
                        'api_key' => '1fdc046964c047839c046964c047833d',
                    ],
        [
                        'station_id' => 'IORIHU72',
                        'name' => 'Orihuela – La Campana',
                        'country' => 'ES',
                        'lat' => 37.945216,
                        'lon' => -0.715166,
                        'elevation' => 24,
                        'api_key' => 'ab200bfde191428ba00bfde191028bb9',
                    ],
        [
                        'station_id' => 'IORIHUEL66',
                        'name' => 'Orihuela – La Campaneta',
                        'country' => 'ES',
                        'lat' => 38.089,
                        'lon' => -0.896,
                        'elevation' => 17,
                        'api_key' => '8a01ef2cfd044d6981ef2cfd04dd694b',
                    ],
        [
                        'station_id' => 'IORIHU119',
                        'name' => 'Orihuela – La Matanza',
                        'country' => 'ES',
                        'lat' => 38.135944,
                        'lon' => -1.010811,
                        'elevation' => 82,
                        'api_key' => '8d9c8d40662d4c9b9c8d40662d5c9bff',
                    ],
        [
                        'station_id' => 'IORIHU96',
                        'name' => 'Orihuela – La Murada – CEIP Maestro Ismael García',
                        'country' => 'ES',
                        'lat' => 38.172698,
                        'lon' => -0.959626,
                        'elevation' => 81,
                        'api_key' => '59e01db677464be3a01db677464be3d3',
                    ],
        [
                        'station_id' => 'IORIHU118',
                        'name' => 'Orihuela – La Murada – Centro Cívico',
                        'country' => 'ES',
                        'lat' => 38.174074,
                        'lon' => -0.964254,
                        'elevation' => 88,
                        'api_key' => 'aab20650189349bcb206501893b9bc95',
                    ],
        [
                        'station_id' => null,
                        'name' => 'Orihuela – La Murada – Los Atocheros',
                        'country' => 'ES',
                        'lat' => 38.185673,
                        'lon' => -0.951797,
                        'elevation' => 103,
                        'api_key' => 'Ecowitt',
                    ],
        [
                        'station_id' => 'IORIHU10',
                        'name' => 'Orihuela – La Regia',
                        'country' => 'ES',
                        'lat' => 37.91,
                        'lon' => -0.743,
                        'elevation' => 38,
                        'api_key' => '8ab637c0318e4b0cb637c0318e8b0ca6',
                    ],
        [
                        'station_id' => 'IORIHU85',
                        'name' => 'Orihuela - La Zenia - VegaFibra Sede Central',
                        'country' => 'ES',
                        'lat' => 37.925331,
                        'lon' => -0.734556,
                        'elevation' => 24,
                        'api_key' => '01731de7febf4ecbb31de7febf2ecb41',
                    ]
        ];

        foreach ($stations as $station) {
            Station::create($station);
        }
    }
}
